<?php

return [
    'title' => 'CGIAR Genebank Accelerator · AoW5 Molecular Characterisation',
    'subtitle' => 'Molecular Characterisation Survey',
    'description' => 'Survey of National Genebank Managers — Strengthening NARS Partner Capacity for Integrated In-situ and Ex-situ Conservation',

    'admin_password' => env('SURVEY_ADMIN_PASSWORD'),

    'sections' => [
        [
            'id' => 'section1',
            'title' => 'About You and Your Institution',
            'subtitle' => 'Seed collections → DNA evidence → data systems → conservation decisions',
            'description' => "Note: If this survey is being filled in by a staff member on behalf of the genebank manager, please provide the genebank manager's details in Q1–Q5 where applicable.",
            'image' => 'section1.jpg',
            'questions' => [
                ['id'=>'q1','number'=>'Q1','text'=>'Full name (optional)','type'=>'text','required'=>false,'placeholder'=>'Your full name'],
                ['id'=>'q2','number'=>'Q2','text'=>'Email address','type'=>'email','required'=>true,'placeholder'=>'your.email@institution.org'],
                ['id'=>'q3','number'=>'Q3','text'=>'Institution / Organization','type'=>'text','required'=>true,'placeholder'=>'Name of your institution'],
                ['id'=>'q4','number'=>'Q4','text'=>'Job title / Position','type'=>'text','required'=>true,'placeholder'=>'Your job title'],
                ['id'=>'q5','number'=>'Q5','text'=>'Country','type'=>'text','required'=>true,'placeholder'=>'Country'],
                ['id'=>'q6','number'=>'Q6','text'=>'Years of experience in genetic resources or molecular biology','type'=>'single','required'=>true,
                 'options'=>[
                     ['label'=>'Less than 2 years','value'=>'<2'],
                     ['label'=>'2–5 years','value'=>'2-5'],
                     ['label'=>'6–10 years','value'=>'6-10'],
                     ['label'=>'More than 10 years','value'=>'>10'],
                 ]],
                ['id'=>'q7','number'=>'Q7','text'=>'Highest degree obtained','type'=>'single','required'=>true,'allow_other'=>true,'other_placeholder'=>'Specify other degree',
                 'options'=>[
                     ['label'=>'Bachelor\'s','value'=>'bachelors'],
                     ['label'=>'Master\'s','value'=>'masters'],
                     ['label'=>'PhD','value'=>'phd'],
                 ['label'=>'Other','value'=>'other'],
                 ]],
                ['id'=>'q8','number'=>'Q8','text'=>'Primary area of expertise / professional role (select all that apply)','type'=>'multi','required'=>true,'allow_other'=>true,'other_placeholder'=>'Specify other expertise',
                 'options'=>[
                     ['label'=>'Breeder','value'=>'breeder'],
                     ['label'=>'Geneticist','value'=>'geneticist'],
                     ['label'=>'Molecular biologist','value'=>'molecular_biologist'],
                     ['label'=>'Bioinformatician','value'=>'bioinformatician'],
                     ['label'=>'Genebank curator / manager','value'=>'curator_manager'],
                 ['label'=>'Other','value'=>'other'],
                 ]],
                ['id'=>'q9','number'=>'Q9','text'=>'Primary crops or species your genebank holds (select all that apply)','type'=>'multi','required'=>true,'allow_other'=>true,'other_placeholder'=>'List up to three other crops/species',
                 'options'=>[
                     ['label'=>'Rice','value'=>'rice'],
                     ['label'=>'Maize','value'=>'maize'],
                     ['label'=>'Sorghum','value'=>'sorghum'],
                     ['label'=>'Pearl millet','value'=>'pearl_millet'],
                     ['label'=>'Cowpea','value'=>'cowpea'],
                     ['label'=>'Groundnut','value'=>'groundnut'],
                     ['label'=>'Yam','value'=>'yam'],
                     ['label'=>'Cassava','value'=>'cassava'],
                     ['label'=>'Soybean','value'=>'soybean'],
                     ['label'=>'Plantain / banana','value'=>'plantain_banana'],
                     ['label'=>'Fonio','value'=>'fonio'],
                     ['label'=>'Forage','value'=>'forage'],
                     ['label'=>'Forest species','value'=>'forest_species'],
                 ['label'=>'Other','value'=>'other'],
                 ]],
            ],
        ],
        [
            'id' => 'section2',
            'title' => 'Sequencing Knowledge and Experience',
            'subtitle' => 'From Molecular Capacity to Applied DSI',
            'description' => 'Note: Questions Q10 and Q11 are general orientation questions. Q12 onwards covers technical detail — genebank managers may wish to consult technical staff members.',
            'image' => 'section2.jpg',
            'questions' => [
                ['id'=>'q10a','number'=>'Q10a','text'=>'Has your genebank ever been involved in generating DNA/RNA sequence data from plant genetic resources?','type'=>'single','required'=>true,
                 'options'=>[['label'=>'Yes','value'=>'yes'],['label'=>'No','value'=>'no'],["label"=>"Don't know","value"=>"dont_know"]]],
                ['id'=>'q10a_description','number'=>'Q10a','text'=>'If yes, briefly describe the purpose','type'=>'longtext','required'=>false,'placeholder'=>'Describe the purpose of generating sequence data','conditional'=>['question_id'=>'q10a','operator'=>'eq','value'=>'yes']],
                ['id'=>'q10b','number'=>'Q10b','text'=>'If YES, what was your level of involvement? (Select all that apply)','type'=>'multi','required'=>false,'allow_other'=>true,'other_placeholder'=>'Specify other involvement','conditional'=>['question_id'=>'q10a','operator'=>'eq','value'=>'yes'],
                 'options'=>[
                     ['label'=>'Only provided plant material for sequencing','value'=>'provided_material'],
                     ['label'=>'Participated in collaborative sequencing projects (external sequencing)','value'=>'collaborative'],
                     ['label'=>'Conducted sequencing in partnership with another institution','value'=>'partnership'],
                     ['label'=>'Performed sequencing in-house (genebank or organisation\'s laboratory)','value'=>'in_house'],
                     ['label'=>'Performed data analysis of sequencing outputs','value'=>'data_analysis'],
                 ['label'=>'Other','value'=>'other'],
                 ]],
                ['id'=>'q11','number'=>'Q11','text'=>'What are the primary objectives for which your genebank would generate and use Digital Sequence Information (DSI) in its genetic resource management? (Select all that apply)','subtext'=>'Note: DSI (Digital Sequence Information) refers to genetic sequence data as discussed under the CBD and ITPGRFA.','type'=>'multi','required'=>true,'allow_other'=>true,'other_placeholder'=>'Specify other objectives',
                 'options'=>[
                     ['label'=>'Basic genetic diversity assessment','value'=>'diversity'],
                     ['label'=>'Duplicate detection and removal of redundant accessions','value'=>'duplicates'],
                     ['label'=>'Core collection development and optimization','value'=>'core_collection'],
                     ['label'=>'Gap analysis (genetic or geographic representation)','value'=>'gap_analysis'],
                     ['label'=>'Population structure analysis','value'=>'population_structure'],
                     ['label'=>'Trait mapping / marker-assisted breeding','value'=>'trait_mapping'],
                     ['label'=>'Phylogenetic and evolutionary studies','value'=>'phylogenetic'],
                     ['label'=>'Conservation prioritisation (in situ / ex situ)','value'=>'conservation'],
                     ['label'=>'Policy or compliance reporting (e.g., Nagoya Protocol, national ABS)','value'=>'policy'],
                 ['label'=>'Other','value'=>'other'],
                 ]],
                ['id'=>'q12','number'=>'Q12','text'=>'Rate your familiarity with the following sequencing technologies (1 = never heard of it; 2 = heard of it, no familiarity; 3 = basic understanding; 4 = practical experience; 5 = expert user)','type'=>'matrix','required'=>true,
                 'rows'=>['Sanger sequencing','Illumina (short-read NGS)','Oxford Nanopore (long-read)','PacBio SMRT','Genotyping-by-sequencing (GBS) / DArTseq','SNP arrays','Reduced representation sequencing (RADseq, etc.)'],
                 'columns'=>['1','2','3','4','5']],
                ['id'=>'q13','number'=>'Q13','text'=>'Which library preparation methods have you used personally? (Select all that apply)','type'=>'multi','required'=>false,'allow_other'=>true,'other_placeholder'=>'Specify other method',
                 'options'=>[
                     ['label'=>'Illumina TruSeq DNA','value'=>'truseq'],
                     ['label'=>'Nextera XT / Flex','value'=>'nextera'],
                     ['label'=>'Oxford Nanopore Ligation Sequencing Kit','value'=>'nanopore_kit'],
                     ['label'=>'PacBio SMRTbell','value'=>'smrtbell'],
                     ['label'=>'DArTseq proprietary protocol','value'=>'dartseq'],
                     ['label'=>'Reduced-representation bisulfite sequencing (RRBS)','value'=>'rrbs'],
                     ['label'=>'None','value'=>'none'],
                 ['label'=>'Other','value'=>'other'],
                 ]],
                ['id'=>'q14','number'=>'Q14','text'=>'Have you ever performed a whole genome sequencing (WGS) experiment?','type'=>'single','required'=>true,
                 'options'=>[['label'=>'Yes, for a plant genome','value'=>'plant'],['label'=>'Yes, for other organisms','value'=>'other'],['label'=>'No','value'=>'no']]],
                ['id'=>'q14_species','number'=>'Q14','text'=>'Species (if plant genome)','type'=>'text','required'=>false,'placeholder'=>'Specify species','conditional'=>['question_id'=>'q14','operator'=>'eq','value'=>'plant']],
                ['id'=>'q15','number'=>'Q15','text'=>'What is the largest number of samples you have processed in a single sequencing run?','type'=>'single','required'=>true,
                 'options'=>[
                     ['label'=>'0 (never processed)','value'=>'0'],
                     ['label'=>'1–23','value'=>'1-23'],
                     ['label'=>'24–95','value'=>'24-95'],
                     ['label'=>'96–383','value'=>'96-383'],
                     ['label'=>'384 or more','value'=>'384+'],
                 ]],
                ['id'=>'q16','number'=>'Q16','text'=>'Do you routinely assess DNA / RNA quality before sequencing? (Select all that apply)','type'=>'multi','required'=>false,
                 'options'=>[
                     ['label'=>'Gel electrophoresis','value'=>'gel'],
                     ['label'=>'Spectrophotometer (e.g., NanoDrop)','value'=>'nanodrop'],
                     ['label'=>'Fluorometric quantification (Qubit, PicoGreen)','value'=>'qubit'],
                     ['label'=>'Bioanalyzer / TapeStation','value'=>'bioanalyzer'],
                     ['label'=>'No quality assessment','value'=>'none'],
                 ]],
                ['id'=>'q17a','number'=>'Q17a','text'=>'Which of the following applications has your genebank used sequencing for? (Select all that apply)','type'=>'multi','required'=>false,
                 'options'=>[
                     ['label'=>'Genetic diversity analysis','value'=>'genetic_diversity'],
                     ['label'=>'Detection of duplicates / redundant accessions in genebank collections','value'=>'duplicates'],
                     ['label'=>'Population structure analysis for curation decisions','value'=>'population_structure'],
                     ['label'=>'Core collection development','value'=>'core_collection'],
                     ['label'=>'Phylogenetic / taxonomic clarification or identification','value'=>'phylogenetic'],
                     ['label'=>'Gap analysis (genetic or geographic coverage)','value'=>'gap_analysis'],
                     ['label'=>'Conservation prioritization','value'=>'conservation'],
                     ['label'=>'None of the above','value'=>'none'],
                 ]],
                ['id'=>'q17b','number'=>'Q17b','text'=>'Has your genebank used sequencing data for any of the following advanced genomic applications? (Select all that apply)','type'=>'multi','required'=>false,
                 'options'=>[
                     ['label'=>'Genome assembly (de novo or reference-guided)','value'=>'genome_assembly'],
                     ['label'=>'Transcriptomics (RNA-Seq)','value'=>'transcriptomics'],
                     ['label'=>'Epigenetics (e.g., bisulfite sequencing)','value'=>'epigenetics'],
                     ['label'=>'Metagenomics / microbiome analysis','value'=>'metagenomics'],
                     ['label'=>'Trait mapping / marker-assisted selection (if applicable)','value'=>'trait_mapping'],
                     ['label'=>'None of the above','value'=>'none'],
                 ]],
                ['id'=>'q18','number'=>'Q18','text'=>'Rate your confidence in interpreting the following types of sequencing output (1 = not confident at all; 2 = slightly confident; 3 = moderately confident; 4 = quite confident; 5 = very confident)','type'=>'matrix','required'=>true,
                 'rows'=>['Quality metrics (FastQC / MultiQC reports)','Read alignment statistics (mapping rate, coverage)','Variant call files (VCF format)','Phylogenetic trees / dendrograms','Population structure plots (PCA, ADMIXTURE)'],
                 'columns'=>['1','2','3','4','5']],
                ['id'=>'q19a','number'=>'Q19a','text'=>'Have you ever received formal training in bioinformatics for NGS data analysis?','type'=>'single','required'=>true,
                 'options'=>[
                     ['label'=>'Yes, university degree or formal academic coursework','value'=>'university'],
                     ['label'=>'Yes, structured professional workshop / training (e.g., EMBL-EBI, Galaxy)','value'=>'workshop'],
                     ['label'=>'Yes, short course or online certification (Coursera, other self-paced training)','value'=>'online'],
                     ['label'=>'Yes, institutional on-the-job training (within genebank or project-based mentoring)','value'=>'on_job'],
                     ['label'=>'No training received','value'=>'none'],
                 ]],
                ['id'=>'q19b','number'=>'Q19b','text'=>'Level of practical application after training','type'=>'single','required'=>true,
                 'options'=>[
                     ['label'=>'Applied occasionally','value'=>'occasionally'],
                     ['label'=>'Applied in routine analyses','value'=>'routine'],
                     ['label'=>'Applied and independently used for data analysis pipelines','value'=>'independent'],
                     ['label'=>'Not applied in practice','value'=>'not_applied'],
                 ]],
                ['id'=>'q20','number'=>'Q20','text'=>'For the crops your genebank holds, do you know their ploidy levels?','type'=>'single','required'=>true,
                 'options'=>[['label'=>'Yes, for all crops','value'=>'all'],['label'=>'Yes, for some crops','value'=>'some'],['label'=>'No','value'=>'no']]],
                ['id'=>'q20_specify','number'=>'Q20','text'=>'Specify which crops','type'=>'text','required'=>false,'placeholder'=>'Specify which crops','conditional'=>['question_id'=>'q20','operator'=>'eq','value'=>'some']],
                ['id'=>'q21','number'=>'Q21','text'=>'Which methods has your genebank used to determine ploidy? (Select all that apply)','type'=>'multi','required'=>false,'allow_other'=>true,'other_placeholder'=>'Specify other method',
                 'options'=>[
                     ['label'=>'Flow cytometry','value'=>'flow_cytometry'],
                     ['label'=>'Chromosome counting (root tip squash)','value'=>'chromosome_counting'],
                     ['label'=>'Inference from sequencing coverage (k-mer analysis)','value'=>'sequencing_coverage'],
                     ['label'=>'Inference from genetic markers (e.g., SSR peak number)','value'=>'genetic_markers'],
                     ['label'=>'Not used any method','value'=>'none'],
                 ['label'=>'Other','value'=>'other'],
                 ]],
                ['id'=>'q22','number'=>'Q22','text'=>'Does your genebank follow standardised protocols (aligned with international guidelines) for collecting passport data and metadata associated with genetic resources?','type'=>'single','required'=>true,
                 'options'=>[
                     ['label'=>'Yes, standardised and complete','value'=>'standardised_complete'],
                     ['label'=>'Yes, but incomplete or inconsistently applied','value'=>'incomplete'],
                     ['label'=>'Yes, but not aligned with international standards','value'=>'not_aligned'],
                     ['label'=>'No standard protocols','value'=>'none'],
                     ['label'=>'Not sure','value'=>'not_sure'],
                 ]],
                ['id'=>'q23','number'=>'Q23','text'=>'What types of metadata does your genebank routinely collect and attach to sequencing projects? (Select all that apply)','type'=>'multi','required'=>false,
                 'options'=>[
                     ['label'=>'Passport data','value'=>'passport'],
                     ['label'=>'Accession history (regeneration, storage, viability tests, distribution)','value'=>'accession_history'],
                     ['label'=>'Phenotypic / field trial data','value'=>'phenotypic'],
                     ['label'=>'Environmental data (GPS, climate)','value'=>'environmental'],
                     ['label'=>'Collection mission records (field notes, photos, expedition details)','value'=>'collection_mission'],
                     ['label'=>'Legal / administrative metadata (SMTA / MTAs / PIC)','value'=>'legal'],
                     ['label'=>'No metadata collected','value'=>'none'],
                 ]],
                ['id'=>'q24a','number'=>'Q24a','text'=>'Which sample types does your genebank typically prepare for sequencing? (Select all that apply)','type'=>'multi','required'=>false,'allow_other'=>true,'other_placeholder'=>'Specify other sample type',
                 'options'=>[
                     ['label'=>'Fresh leaf tissue','value'=>'fresh_leaf'],
                     ['label'=>'Silica-dried tissues','value'=>'silica_dried'],
                     ['label'=>'Lyophilised material','value'=>'lyophilised'],
                     ['label'=>'Seeds','value'=>'seeds'],
                 ['label'=>'Other','value'=>'other'],
                 ]],
                ['id'=>'q24b','number'=>'Q24b','text'=>'What molecular material does your genebank use for sequencing?','type'=>'single','required'=>true,
                 'options'=>[['label'=>'DNA','value'=>'dna'],['label'=>'RNA','value'=>'rna'],['label'=>'Both DNA and RNA','value'=>'both'],['label'=>'Not applicable','value'=>'na']]],
                ['id'=>'q25','number'=>'Q25','text'=>'Does your genebank follow standardised SOPs for DNA / RNA extraction?','type'=>'single','required'=>true,
                 'options'=>[
                     ['label'=>'Yes, internationally recognised protocols','value'=>'international'],
                     ['label'=>'Yes, internal SOPs','value'=>'internal'],
                     ['label'=>'SOPs are under development','value'=>'under_development'],
                     ['label'=>'No formal SOPs','value'=>'none'],
                 ]],
            ],
        ],
        [
            'id' => 'section3',
            'title' => 'Infrastructure and Resources',
            'subtitle' => 'Laboratory, Data, and Institutional Readiness',
            'image' => 'section3.jpg',
            'questions' => [
                ['id'=>'q26','number'=>'Q26','text'=>'Does your genebank laboratory have the following equipment available for routine use? (1 = not available; 2 = available but not functional; 3 = rarely used; 4 = occasionally used; 5 = routinely used)','type'=>'matrix','required'=>true,
                 'rows'=>['PCR thermocycler','Real-time PCR (qPCR) machine','DNA sequencer (any type)','Nanopore MinION / Flongle','Gel electrophoresis system','NanoDrop / spectrophotometer','Qubit / fluorometer','Bioanalyzer / TapeStation','Flow cytometer (for ploidy estimation)'],
                 'columns'=>['1','2','3','4','5']],
                ['id'=>'q27','number'=>'Q27','text'=>'Does your genebank have access to a centralised sequencing facility (in-country or regional)?','type'=>'single','required'=>true,
                 'options'=>[['label'=>'Yes, on-site','value'=>'on_site'],['label'=>'Yes, off-site (within country)','value'=>'off_site'],['label'=>'Yes, regional (shared across borders)','value'=>'regional'],['label'=>'No access','value'=>'no_access']]],
                ['id'=>'q28','number'=>'Q28','text'=>'What is the typical turnaround time to receive sequencing data after sending samples?','type'=>'single','required'=>true,
                 'options'=>[
                     ['label'=>'Less than 2 weeks','value'=>'<2_weeks'],
                     ['label'=>'2–4 weeks','value'=>'2-4_weeks'],
                     ['label'=>'1–3 months','value'=>'1-3_months'],
                     ['label'=>'More than 3 months','value'=>'>3_months'],
                     ['label'=>'Not applicable (we do not send samples)','value'=>'na'],
                 ]],
                ['id'=>'q29a','number'=>'Q29a','text'=>'Does your genebank have computing infrastructure to analyse raw sequencing data (e.g., ≥32 GB RAM, multi-core CPU)?','type'=>'single','required'=>true,
                 'options'=>[['label'=>'Yes, local workstation','value'=>'local_workstation'],['label'=>'Yes, institutional server / cluster','value'=>'server_cluster'],['label'=>'Yes, cloud computing (AWS, Google Cloud, etc.)','value'=>'cloud'],['label'=>'No, we rely on external collaborators','value'=>'external']]],
                ['id'=>'q29b','number'=>'Q29b','text'=>'If yes, are these facilities sufficient and functional for analysing raw sequencing data?','type'=>'single','required'=>false,'conditional'=>['question_id'=>'q29a','operator'=>'neq','value'=>'external'],
                 'options'=>[
                     ['label'=>'Yes, fully sufficient for routine analysis','value'=>'fully_sufficient'],
                     ['label'=>'Partially sufficient (can handle small datasets only)','value'=>'partially'],
                     ['label'=>'Available but not functional (hardware / software limitations)','value'=>'not_functional'],
                     ['label'=>'Available but lack bioinformatics software / licenses','value'=>'lack_software'],
                 ]],
                ['id'=>'q30','number'=>'Q30','text'=>'Which of the following bioinformatics tools has your genebank installed or used locally? (Select all that apply)','type'=>'multi','required'=>false,'allow_other'=>true,'other_placeholder'=>'Specify other tools',
                 'options'=>[
                     ['label'=>'FastQC','value'=>'fastqc'],
                     ['label'=>'Trimmomatic','value'=>'trimmomatic'],
                     ['label'=>'BWA','value'=>'bwa'],
                     ['label'=>'Bowtie2','value'=>'bowtie2'],
                     ['label'=>'SAMtools','value'=>'samtools'],
                     ['label'=>'GATK','value'=>'gatk'],
                     ['label'=>'BCFtools','value'=>'bcftools'],
                     ['label'=>'PLINK','value'=>'plink'],
                     ['label'=>'TASSEL','value'=>'tassel'],
                     ['label'=>'R / Bioconductor','value'=>'r_bioconductor'],
                     ['label'=>'Python (Biopython)','value'=>'python'],
                     ['label'=>'Galaxy platform','value'=>'galaxy'],
                 ['label'=>'Other','value'=>'other'],
                 ]],
                ['id'=>'q31','number'=>'Q31','text'=>'Is your genebank able to store large sequencing datasets (≥1 TB) reliably?','type'=>'single','required'=>true,
                 'options'=>[['label'=>'Yes, with regular backups','value'=>'with_backups'],['label'=>'Yes, but limited capacity','value'=>'limited'],['label'=>'No, we lack storage infrastructure','value'=>'none']]],
                ['id'=>'q32','number'=>'Q32','text'=>'Does your genebank have a dedicated person or team responsible for bioinformatics support?','type'=>'single','required'=>true,
                 'options'=>[['label'=>'Yes, full-time','value'=>'full_time'],['label'=>'Yes, part-time / shared','value'=>'part_time'],['label'=>'No, we rely on external collaborators','value'=>'external'],['label'=>'No support available','value'=>'none']]],
                ['id'=>'q33','number'=>'Q33','text'=>'Does your genebank have a long-term vision / strategy for molecular characterisation?','type'=>'single','required'=>true,
                 'options'=>[['label'=>'Yes, documented strategy','value'=>'documented'],['label'=>'Informal plan','value'=>'informal'],['label'=>'No strategic direction','value'=>'none'],['label'=>'Under development','value'=>'under_development'],['label'=>'Aligned with organisational policy','value'=>'aligned']]],
                ['id'=>'q34','number'=>'Q34','text'=>"What is the most significant constraint affecting your genebank's sequencing work?",'type'=>'single','required'=>true,
                 'options'=>[
                     ['label'=>'Absence of molecular lab','value'=>'no_lab'],
                     ['label'=>'High cost of molecular laboratory set-up','value'=>'lab_cost'],
                     ['label'=>'High cost of sequencing runs','value'=>'sequencing_cost'],
                     ['label'=>'Limited funding for bioinformatics staff','value'=>'bioinfo_staff'],
                     ['label'=>'Limited computing / storage investment','value'=>'computing'],
                     ['label'=>'Limited staff with molecular analysis expertise','value'=>'staff_expertise'],
                 ]],
                ['id'=>'q35','number'=>'Q35','text'=>'What annual budget (approximate) does your genebank allocate for molecular characterisation?','type'=>'single','required'=>true,
                 'options'=>[
                     ['label'=>'$0–$5,000','value'=>'0-5k'],
                     ['label'=>'$5,000–$20,000','value'=>'5k-20k'],
                     ['label'=>'$20,000–$50,000','value'=>'20k-50k'],
                     ['label'=>'Greater than $50,000','value'=>'>50k'],
                     ['label'=>'Not allocated / No dedicated budget','value'=>'not_allocated'],
                     ['label'=>'Not sure','value'=>'not_sure'],
                 ]],
                ['id'=>'q36a','number'=>'Q36a','text'=>'Does your genebank collaborate with external organisations for molecular characterisation of plant genetic resources (PGRs)?','type'=>'single','required'=>true,
                 'options'=>[['label'=>'Yes','value'=>'yes'],['label'=>'No','value'=>'no'],['label'=>'Not sure','value'=>'not_sure']]],
                ['id'=>'q36b_partner_name','number'=>'Q36b','text'=>'Name of partner organisation(s)','type'=>'text','required'=>false,'placeholder'=>'Partner organisation name','conditional'=>['question_id'=>'q36a','operator'=>'eq','value'=>'yes']],
                ['id'=>'q36b_partner_country','number'=>'Q36b','text'=>'Country / region of partner','type'=>'text','required'=>false,'placeholder'=>'Partner country or region','conditional'=>['question_id'=>'q36a','operator'=>'eq','value'=>'yes']],
                ['id'=>'q36c','number'=>'Q36c','text'=>'Nature of collaboration — Is the molecular characterisation part of a broader research collaboration or project?','type'=>'single','required'=>false,'conditional'=>['question_id'=>'q36a','operator'=>'eq','value'=>'yes'],
                 'options'=>[['label'=>'Yes','value'=>'yes'],['label'=>'No','value'=>'no'],['label'=>'Not sure','value'=>'not_sure']]],
                ['id'=>'q36c_description','number'=>'Q36c','text'=>'If yes, briefly describe the broader collaboration','type'=>'longtext','required'=>false,'placeholder'=>'Describe the collaboration','conditional'=>['question_id'=>'q36c','operator'=>'eq','value'=>'yes']],
                ['id'=>'q36d','number'=>'Q36d','text'=>'Roles and contributions — Please describe what your genebank received as part of that partnership to generate DSI. Indicate if your genebank received:','type'=>'multi','required'=>false,'allow_other'=>true,'other_placeholder'=>'Specify other contributions','conditional'=>['question_id'=>'q36a','operator'=>'eq','value'=>'yes'],
                 'options'=>[
                     ['label'=>'Training','value'=>'training'],
                     ['label'=>'Equipment','value'=>'equipment'],
                     ['label'=>'Financial support','value'=>'financial'],
                     ['label'=>'Knowledge products','value'=>'knowledge_products'],
                     ['label'=>'Co-authorship in publications or other knowledge products','value'=>'co_authorship'],
                     ['label'=>'Access to genetic resources from outside your organisation','value'=>'access_gr'],
                     ['label'=>'Access to DSI generated from outside your organisation','value'=>'access_dsi'],
                     ['label'=>'Not applicable / none of the above','value'=>'na'],
                 ['label'=>'Other','value'=>'other'],
                 ]],
                ['id'=>'q36e','number'=>'Q36e','text'=>'Frequency of collaboration','type'=>'single','required'=>false,'conditional'=>['question_id'=>'q36a','operator'=>'eq','value'=>'yes'],
                 'options'=>[['label'=>'Continuous / ongoing','value'=>'continuous'],['label'=>'Annual','value'=>'annual'],['label'=>'Occasional (project-based)','value'=>'occasional'],['label'=>'One-off','value'=>'one_off'],['label'=>'Not sure','value'=>'not_sure']]],
                ['id'=>'q36e_coordination','number'=>'Q36e','text'=>'How are activities and results monitored or coordinated?','type'=>'longtext','required'=>false,'placeholder'=>'Describe monitoring and coordination','conditional'=>['question_id'=>'q36a','operator'=>'eq','value'=>'yes']],
            ],
        ],
        [
            'id' => 'section4',
            'title' => 'Data Management and Sharing',
            'subtitle' => 'CGIAR Genebank Accelerator Survey Module',
            'image' => 'section4.jpg',
            'questions' => [
                ['id'=>'q37','number'=>'Q37','text'=>'Which public repositories has your genebank submitted sequence data to? (Select all that apply)','type'=>'multi','required'=>false,'allow_other'=>true,'other_placeholder'=>'Specify other repository',
                 'options'=>[
                     ['label'=>'NCBI (SRA / GenBank)','value'=>'ncbi'],
                     ['label'=>'EMBL-EBI (ENA)','value'=>'embl_ebi'],
                     ['label'=>'DDBJ','value'=>'ddbj'],
                     ['label'=>'Dryad','value'=>'dryad'],
                     ['label'=>'Figshare','value'=>'figshare'],
                     ['label'=>'Indian Biological Data Center','value'=>'ibdc'],
                     ['label'=>'Zenodo','value'=>'zenodo'],
                     ['label'=>'CNSA (China National GeneBank Sequence Archive)','value'=>'cnsa'],
                     ['label'=>'Dataverse','value'=>'dataverse'],
                     ['label'=>'None','value'=>'none'],
                 ['label'=>'Other','value'=>'other'],
                 ]],
                ['id'=>'q38','number'=>'Q38','text'=>'What are the three most pressing needs for your genebank to enhance its use of sequencing in genetic resource management? (Rank your top 3: write 1 = most pressing, 2 = second most pressing, 3 = third most pressing)','subtext'=>'Note: Please select exactly three needs and rank them.','type'=>'ranking','required'=>true,'min_selections'=>3,'max_selections'=>3,
                 'options'=>[
                     ['label'=>'Access to sequencing equipment or facilities','value'=>'sequencing_equipment'],
                     ['label'=>'Funding for sequencing runs and related laboratory costs','value'=>'funding'],
                     ['label'=>'Bioinformatics capacity development (training and staffing)','value'=>'bioinformatics_capacity'],
                     ['label'=>'Standardised protocols and SOPs','value'=>'sops'],
                     ['label'=>'Access to reference genomes and genomic databases','value'=>'reference_genomes'],
                     ['label'=>'Data storage, computing infrastructure and cloud services','value'=>'data_storage'],
                     ['label'=>'Policy guidance on DSI and benefit-sharing','value'=>'policy_guidance'],
                     ['label'=>'Legal support for data sharing (MTA / SMTA)','value'=>'legal_support'],
                     ['label'=>'Other','value'=>'other'],
                 ]],
            ],
        ],
        [
            'id' => 'section5',
            'title' => 'Genetic Resources and DSI Policies, Laws and Experiences',
            'subtitle' => 'Laws and Experiences',
            'description' => "This section assesses your genebank's knowledge of, and experience with, the policy and legal frameworks governing Digital Sequence Information (DSI) and genetic resources.",
            'image' => 'section5.jpg',
            'questions' => [
                ['id'=>'q39','number'=>'Q39','text'=>"Rate your genebank's knowledge of benefit-sharing frameworks related to the use of genetic resources and DSI (1 = no familiarity; 2 = heard of it, no understanding; 3 = basic understanding; 4 = good understanding; 5 = expert knowledge)",'type'=>'matrix','required'=>true,
                 'rows'=>['ITPGRFA multilateral system (benefit-sharing for Annex 1 crops)','CBD Nagoya Protocol (access and benefit-sharing)','CBD Decision 15/9 (DSI benefit-sharing framework)','CBD Decision 16/2 (multilateral mechanism for DSI)','SMTA / Standard Material Transfer Agreement'],
                 'columns'=>['1','2','3','4','5']],
                ['id'=>'q40','number'=>'Q40','text'=>'Does your genebank, or the organisation that hosts your genebank, have a dedicated legal or policy unit that handles genetic resource intellectual property, MTAs, or benefit-sharing agreements?','type'=>'single','required'=>true,
                 'options'=>[['label'=>'Yes','value'=>'yes'],['label'=>'No','value'=>'no']]],
                ['id'=>'q41','number'=>'Q41','text'=>'Are you aware of any national laws or regulations in your country that address (or are under development to address) the access, use, or sharing of DSI?','type'=>'single','required'=>true,
                 'options'=>[['label'=>'Yes, existing law / regulation','value'=>'existing'],['label'=>'Yes, draft or under development','value'=>'draft'],['label'=>'No','value'=>'no'],["label"=>"Don't know","value"=>"dont_know"]]],
                ['id'=>'q41_description','number'=>'Q41','text'=>'If yes, briefly name and describe the law and its relevance to DSI','type'=>'longtext','required'=>false,'placeholder'=>'Describe the law and its relevance','conditional'=>['question_id'=>'q41','operator'=>'eq','value'=>'existing']],
                ['id'=>'q42','number'=>'Q42','text'=>'Does your genebank have a policy or guidelines related to the generation, use, sharing, or publication of DSI from genetic resources?','type'=>'single','required'=>true,
                 'options'=>[['label'=>'Yes','value'=>'yes'],['label'=>'No','value'=>'no'],['label'=>'Under development','value'=>'under_development'],["label"=>"Don't know","value"=>"dont_know"]]],
                ['id'=>'q42_description','number'=>'Q42','text'=>'If yes or under development, please provide a brief description','type'=>'longtext','required'=>false,'placeholder'=>'Describe the policy or guidelines','conditional'=>['question_id'=>'q42','operator'=>'in','value'=>['yes','under_development']]],
                ['id'=>'q43','number'=>'Q43','text'=>'Does your genebank experience uncertainty about how international or national laws and policies affect the use of DSI associated with its collections?','type'=>'single','required'=>true,
                 'options'=>[['label'=>'Yes, considerable uncertainty','value'=>'considerable'],['label'=>'Yes, some uncertainty','value'=>'some'],['label'=>'No, policies are clear','value'=>'clear'],["label"=>"Don't know","value"=>"dont_know"]]],
                ['id'=>'q43_description','number'=>'Q43','text'=>'If yes, briefly describe the main areas of uncertainty','type'=>'longtext','required'=>false,'placeholder'=>'Describe areas of uncertainty','conditional'=>['question_id'=>'q43','operator'=>'eq','value'=>'considerable']],
                ['id'=>'q44','number'=>'Q44','text'=>'Has your genebank generated DSI as part of a research partnership with other organisations?','type'=>'single','required'=>true,
                 'options'=>[['label'=>'Yes','value'=>'yes'],['label'=>'No','value'=>'no']]],
                ['id'=>'q44_partner_origin','number'=>'Q44','text'=>'If yes, were the partnering organisations','type'=>'single','required'=>false,'conditional'=>['question_id'=>'q44','operator'=>'eq','value'=>'yes'],
                 'options'=>[['label'=>'From my country','value'=>'domestic'],['label'=>'From another country or countries','value'=>'international'],['label'=>'Both','value'=>'both']]],
                ['id'=>'q45','number'=>'Q45','text'=>'If you answered yes to Q44, as part of that partnership to generate DSI, please indicate if your genebank received any of the following benefits from the partnership: (Select all that apply)','type'=>'multi','required'=>false,'allow_other'=>true,'other_placeholder'=>'Specify other benefits','conditional'=>['question_id'=>'q44','operator'=>'eq','value'=>'yes'],
                 'options'=>[
                     ['label'=>'Training','value'=>'training'],
                     ['label'=>'Equipment','value'=>'equipment'],
                     ['label'=>'Financial support','value'=>'financial'],
                     ['label'=>'Knowledge products','value'=>'knowledge_products'],
                     ['label'=>'Co-authorship in publications or other knowledge products','value'=>'co_authorship'],
                     ['label'=>'Access to genetic resources from outside your organisation','value'=>'access_gr'],
                     ['label'=>'Access to DSI generated from outside your organisation','value'=>'access_dsi'],
                     ['label'=>'Not applicable / none of the above','value'=>'na'],
                 ['label'=>'Other','value'=>'other'],
                 ]],
                ['id'=>'q46','number'=>'Q46','text'=>'Which of the following would most help your genebank address policy-related uncertainties regarding DSI? (Select up to three)','type'=>'multi','required'=>false,'allow_other'=>true,'other_placeholder'=>'Specify other help needed','max_selections'=>3,
                 'options'=>[
                     ['label'=>'Short course on DSI and the evolving policy landscape','value'=>'short_course'],
                     ['label'=>'Model MTAs (including the ITPGRFA\'s SMTA) and legal templates for sequencing projects','value'=>'model_mtas'],
                     ['label'=>'Workshop on policies related to the management of DSI','value'=>'workshop'],
                     ['label'=>'Guidance on benefit-sharing arrangements for DSI (monetary and non-monetary)','value'=>'benefit_sharing'],
                     ['label'=>'Database management in compliance with international norms','value'=>'database_management'],
                 ['label'=>'Other','value'=>'other'],
                 ]],
            ],
        ],
        [
            'id' => 'section6',
            'title' => 'Interest in Future Collaborative DSI Generation for Genebank Use',
            'subtitle' => 'Future Collaborative DSI Generation',
            'description' => "The following questions explore your genebank's potential interest in developing proposals, together with CGIAR, to generate DSI specifically for genebank management purposes.",
            'image' => 'section6.jpg',
            'questions' => [
                ['id'=>'q47','number'=>'Q47','text'=>'Would your genebank be interested in developing a proposal with CGIAR centres to generate DSI from genebank accessions for use in breeding programmes?','type'=>'single','required'=>true,
                 'options'=>[['label'=>'Very interested','value'=>'very_interested'],['label'=>'Somewhat interested','value'=>'somewhat_interested'],['label'=>'Neutral / undecided','value'=>'neutral'],['label'=>'Not interested','value'=>'not_interested']]],
                ['id'=>'q47_comment','number'=>'Q47','text'=>'Comment (if applicable)','type'=>'longtext','required'=>false,'placeholder'=>'Add any comments about your interest','conditional'=>['question_id'=>'q47','operator'=>'eq','value'=>'not_interested']],
                ['id'=>'q48','number'=>'Q48','text'=>'If interested, what type of DSI generation would be most relevant for your genebank? (Select all that apply)','type'=>'multi','required'=>false,'allow_other'=>true,'other_placeholder'=>'Specify other type','conditional'=>['question_id'=>'q47','operator'=>'neq','value'=>'not_interested'],
                 'options'=>[
                     ['label'=>'Whole genome sequencing of genebank accessions','value'=>'wgs'],
                     ['label'=>'Genotyping-by-sequencing or similar reduced-representation sequencing for diversity panels','value'=>'gbs'],
                     ['label'=>'Targeted sequencing of specific genes / traits','value'=>'targeted'],
                     ['label'=>'Transcriptomics for stress responses','value'=>'transcriptomics'],
                 ['label'=>'Other','value'=>'other'],
                 ]],
                ['id'=>'q49','number'=>'Q49','text'=>'What type of agreements would your genebank require to participate in such collaborative DSI generation? (Select all that apply)','type'=>'multi','required'=>false,'allow_other'=>true,'other_placeholder'=>'Specify other agreement type',
                 'options'=>[
                     ['label'=>'Material Transfer Agreement (MTA) for samples','value'=>'mta'],
                     ['label'=>'Data-Sharing Agreement explicitly covering DSI','value'=>'dsa'],
                     ['label'=>'Collaboration Agreement (e.g., joint research, publication rights)','value'=>'collaboration'],
                     ['label'=>'Benefit-sharing arrangement (monetary or non-monetary)','value'=>'benefit_sharing'],
                     ['label'=>'No special agreement beyond existing policies','value'=>'none'],
                 ['label'=>'Other','value'=>'other'],
                 ]],
                ['id'=>'q50','number'=>'Q50','text'=>'What support from CGIAR would most help your genebank engage in collaborative DSI generation? (Rank your top 3: 1 = most important)','type'=>'ranking','required'=>true,'min_selections'=>3,'max_selections'=>3,
                 'options'=>[
                     ['label'=>'Technical training (bioinformatics / sequencing)','value'=>'technical_training'],
                     ['label'=>'Equipment or infrastructure grants','value'=>'equipment'],
                     ['label'=>'Legal / MTA template support','value'=>'legal'],
                     ['label'=>'Co-funding for sequencing runs','value'=>'co_funding'],
                     ['label'=>'Access to reference databases and pipelines','value'=>'reference_databases'],
                     ['label'=>'Policy guidance on DSI benefit-sharing','value'=>'policy_guidance'],
                     ['label'=>'Other','value'=>'other'],
                 ]],
                ['id'=>'q51','number'=>'Q51','text'=>'What type of long-term collaboration would your genebank prefer with CGIAR? (Select all that apply)','type'=>'multi','required'=>false,
                 'options'=>[
                     ['label'=>'Co-development of molecular analysis pipelines','value'=>'co_develop_pipelines'],
                     ['label'=>'Joint training programmes (short courses, workshops)','value'=>'joint_training'],
                     ['label'=>'Shared infrastructure / regional hubs','value'=>'shared_infrastructure'],
                     ['label'=>'Capacity development or internships','value'=>'capacity_development'],
                     ['label'=>'Joint research projects and publications','value'=>'joint_research'],
                     ['label'=>'Shared data management systems (bioinformatics platforms, genomic databases)','value'=>'shared_data'],
                     ['label'=>'Policy and standards development (ABS, DSI, data governance)','value'=>'policy_standards'],
                 ]],
                ['id'=>'q52','number'=>'Q52','text'=>'What major improvements have occurred at your genebank due to molecular characterisation?','type'=>'longtext','required'=>false,'placeholder'=>'Describe major improvements...'],
                ['id'=>'q53','number'=>'Q53','text'=>'What policy issues would you want to address in the context of a joint DSI initiative with CGIAR?','type'=>'longtext','required'=>false,'placeholder'=>'Describe policy issues...'],
                ['id'=>'q54','number'=>'Q54','text'=>'Any additional comments or suggestions regarding molecular characterisation capacity at your genebank, especially concerning potential collaborative DSI projects?','type'=>'longtext','required'=>false,'placeholder'=>'Additional comments or suggestions...'],
            ],
        ],
    ],
];
