-- RBCA Supabase backend schema.
-- Use Supabase Auth for identity. Never expose the service role key in the Vite app.

create extension if not exists pgcrypto;

create or replace function public.set_updated_at()
returns trigger language plpgsql as $$
begin
    new.updated_at = now();
    return new;
end;
$$;

create or replace function public.has_exact_ranks(value jsonb)
returns boolean language sql immutable as $$
    select jsonb_typeof(value) = 'array'
       and jsonb_array_length(value) = 3
       and (select array_agg(item::int order by item::int)
            from jsonb_array_elements_text(value) item) = array[1, 2, 3];
$$;

create table public.profiles (
    id uuid primary key references auth.users(id) on delete cascade,
    display_name text,
    institution text,
    role text not null default 'respondent' check (role in ('respondent', 'admin')),
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

create table public.accessions (
    id bigint generated by default as identity primary key,
    accession varchar(20) not null unique,
    name varchar(50) not null,
    doi varchar(20),
    taxon varchar(20),
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

create table public.feeds (
    id bigint generated by default as identity primary key,
    email text not null, institution text, accession text,
    cgiar_3 boolean not null default false, nars_3 boolean not null default false,
    nars_3_exchange boolean not null default false, nars_3_exp_1 text,
    nars_3_share boolean not null default false, nars_3_exp_2 text,
    nars_3_send boolean not null default false, nars_3_exp_3 text,
    nars_3_evaluation boolean not null default false, nars_3_exp_4 text,
    university_3 boolean not null default false, individual_3 boolean not null default false,
    famer_3 boolean not null default false, requested boolean not null default false,
    drought_6 boolean not null default false, heat_6 boolean not null default false,
    flooding_6 boolean not null default false, salinity_6 boolean not null default false,
    insect_6 boolean not null default false, pest_6 boolean not null default false,
    disease_6 boolean not null default false, yield_6 boolean not null default false,
    quality_6 boolean not null default false, inevaluation_7 boolean not null default false,
    publication_7 boolean not null default false, characterization_7 boolean not null default false,
    identification_7 boolean not null default false, markers_7 boolean not null default false,
    expansion_7 boolean not null default false, breeding_7 boolean not null default false,
    cultivar_7 boolean not null default false, information_7 boolean not null default false,
    planting_7 boolean not null default false, drought_8 boolean not null default false,
    heat_8 boolean not null default false, salinity_8 boolean not null default false,
    insect_8 boolean not null default false, pest_8 boolean not null default false,
    disease_8 boolean not null default false, yield_8 boolean not null default false,
    quality_8 boolean not null default false, waterlogging_8 boolean not null default false,
    other_8 text, percent numeric(8,5) not null default 0,
    seedrate integer not null default 0, servicerate integer not null default 0,
    comments text, created_at timestamptz not null default now(), updated_at timestamptz not null default now()
);

create table public.feedsws (
    id bigint generated by default as identity primary key, name text not null, email text not null,
    institution text, contact text, stress_traits text, facilities text,
    hotspot_location varchar(6), location text, rice_genetic varchar(6),
    created_at timestamptz not null default now(), updated_at timestamptz not null default now()
);

create table public.feeders (
    id bigint generated by default as identity primary key,
    email text not null unique, created_at timestamptz not null default now(), updated_at timestamptz not null default now()
);

create table public.survey_responses (
    id bigint generated by default as identity primary key,
    response_uuid uuid not null unique default gen_random_uuid(),
    respondent_name text, email text not null, email_normalized text not null unique,
    institution text, position text, country text, answers jsonb not null default '{}'::jsonb,
    q34_constraint text, q38_ranked_needs jsonb, q43_uncertainty text, q50_ranked_support jsonb,
    submitted_at timestamptz not null default now(), created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    constraint q38_ranked_needs_exact check (q38_ranked_needs is null or public.has_exact_ranks(q38_ranked_needs)),
    constraint q50_ranked_support_exact check (q50_ranked_support is null or public.has_exact_ranks(q50_ranked_support))
);

create table public.survey_drafts (
    id bigint generated by default as identity primary key,
    draft_uuid uuid not null unique default gen_random_uuid(), email text,
    answers jsonb not null default '{}'::jsonb, current_section smallint not null default 1 check (current_section between 1 and 6),
    last_saved_at timestamptz not null default now(), created_at timestamptz not null default now(), updated_at timestamptz not null default now()
);

create table public.contact_messages (
    id bigint generated by default as identity primary key,
    name text not null, email text not null, subject text not null, message text not null,
    status text not null default 'new' check (status in ('new', 'read', 'replied', 'closed')),
    created_at timestamptz not null default now(), updated_at timestamptz not null default now()
);

create table public.admin_audit_log (
    id bigint generated by default as identity primary key,
    actor_id uuid references auth.users(id) on delete set null,
    action text not null, resource text, metadata jsonb not null default '{}'::jsonb,
    created_at timestamptz not null default now()
);

create index accessions_name_idx on public.accessions (name);
create index feeds_email_idx on public.feeds (email);
create index feedsws_email_idx on public.feedsws (email);
create index survey_responses_country_idx on public.survey_responses (country);
create index contact_messages_status_idx on public.contact_messages (status);

create trigger profiles_updated_at before update on public.profiles for each row execute function public.set_updated_at();
create trigger feeds_updated_at before update on public.feeds for each row execute function public.set_updated_at();
create trigger feedsws_updated_at before update on public.feedsws for each row execute function public.set_updated_at();
create trigger feeders_updated_at before update on public.feeders for each row execute function public.set_updated_at();
create trigger accessions_updated_at before update on public.accessions for each row execute function public.set_updated_at();
create trigger survey_responses_updated_at before update on public.survey_responses for each row execute function public.set_updated_at();
create trigger survey_drafts_updated_at before update on public.survey_drafts for each row execute function public.set_updated_at();
create trigger contact_messages_updated_at before update on public.contact_messages for each row execute function public.set_updated_at();

alter table public.profiles enable row level security;
alter table public.accessions enable row level security;
alter table public.feeds enable row level security;
alter table public.feedsws enable row level security;
alter table public.feeders enable row level security;
alter table public.survey_responses enable row level security;
alter table public.survey_drafts enable row level security;
alter table public.contact_messages enable row level security;
alter table public.admin_audit_log enable row level security;

create policy "Public reads accession catalogue" on public.accessions for select to anon, authenticated using (true);
create policy "Users read own profile" on public.profiles for select to authenticated using (id = auth.uid());
create policy "Users update own profile" on public.profiles for update to authenticated using (id = auth.uid()) with check (id = auth.uid());
create policy "Authenticated users read own drafts" on public.survey_drafts for select to authenticated using (email = lower(auth.jwt() ->> 'email'));
create policy "Authenticated users create own drafts" on public.survey_drafts for insert to authenticated with check (email = lower(auth.jwt() ->> 'email'));
create policy "Authenticated users update own drafts" on public.survey_drafts for update to authenticated using (email = lower(auth.jwt() ->> 'email')) with check (email = lower(auth.jwt() ->> 'email'));
create policy "Anyone can submit contact messages" on public.contact_messages for insert to anon, authenticated with check (length(trim(name)) > 0 and length(trim(message)) > 0);

-- Survey/feedback/NARS writes and all administrative reads belong behind Edge Functions or a trusted server role.
revoke all on public.feeds, public.feedsws, public.feeders, public.survey_responses, public.admin_audit_log from anon, authenticated;
revoke insert, update, delete on public.accessions from anon, authenticated;
