-- Admin-managed surveys, newsletter subscriptions, and role-safe profiles.

drop policy if exists "Users update own profile" on public.profiles;

create table public.surveys (
    id bigint generated by default as identity primary key,
    slug text not null unique,
    title text not null,
    description text,
    questions jsonb not null default '[]'::jsonb,
    status text not null default 'draft' check (status in ('draft', 'published', 'archived')),
    created_by uuid references auth.users(id) on delete set null,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

create table public.newsletter_subscribers (
    id bigint generated by default as identity primary key,
    email text not null,
    email_normalized text not null unique,
    status text not null default 'subscribed' check (status in ('subscribed', 'unsubscribed')),
    subscribed_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

alter table public.survey_responses add column survey_slug text;
create index survey_responses_survey_slug_idx on public.survey_responses (survey_slug);
alter table public.survey_responses drop constraint if exists survey_responses_email_normalized_key;
alter table public.survey_responses add constraint survey_responses_survey_email_unique unique (survey_slug, email_normalized);

create index surveys_status_idx on public.surveys (status);
create index newsletter_subscribers_status_idx on public.newsletter_subscribers (status);

create trigger surveys_updated_at before update on public.surveys for each row execute function public.set_updated_at();
create trigger newsletter_subscribers_updated_at before update on public.newsletter_subscribers for each row execute function public.set_updated_at();

alter table public.surveys enable row level security;
alter table public.newsletter_subscribers enable row level security;

create policy "Anyone can subscribe to newsletter" on public.newsletter_subscribers
    for insert to anon, authenticated
    with check (email_normalized = lower(trim(email)) and length(trim(email)) > 3);